import { SettingsForm } from './Settings.interface'

export const settingsDefaultValues: SettingsForm = {
	email: '',
	password: '',
	height: null,
	weight: null,
	avatar: null,
	gender: 'male',
	birthdate: '',
	mealFrequency: null,
	favoriteFoods: { values: [], customInputs: {} },
	medicalRestrictions: { values: [], customInputs: {} },
	cookingPreferences: { values: [], customInputs: {} },
	allergies: { values: [], customInputs: {} },
	dietType: { values: [], customInputs: {} },
	personalRestrictions: { values: [], customInputs: {} },
	mealTimePreferences: { values: [], customInputs: {} },
	religiousRestrictions: { values: [], customInputs: {} },
	cookingTimeConstraints: { values: [], customInputs: {} },
	nutritionPreferences: { values: [], customInputs: {} },
	seasonalPreferences: { values: [], customInputs: {} },
	budgetPreferences: { values: [], customInputs: {} },
	cookingExperience: { values: [], customInputs: {} },
	nutritionGoal: { values: [], customInputs: {} },
	flexibleDayFrequency: { values: [], customInputs: {} },
  flexibleDayType: { values: [], customInputs: {} },
  flexibleDays: { values: [], customInputs: {} },
	activityLevel: { values: [], customInputs: {} },
	advancedSettings: {
		vitaminD3: null,
		ferritin: null,
		vitaminB12: null,
		vitaminC: null,
		vitaminA: null,
		vitaminE: null,
		vitaminK: null,
		iron: null,
		magnesium: null,
		calcium: null,
		potassium: null,
		sodium: null,
		phosphorus: null,
		zinc: null,
		totalCholesterol: null,
		ldlCholesterol: null,
		triglycerides: null,
		fastingGlucose: null,
		hba1c: null,
		homaIr: null,
		insulin: null,
		cortisol: null,
		testosterone: null,
		estrogen: null,
		tsh: null,
		t3Free: null,
		t4Free: null,
		antiTpo: null,
		albumin: null,
		totalProtein: null,
		creatinine: null,
		crp: null,
		homocysteine: null,
		glutathione: null,
		mda: null,
		totalAntioxidantStatus: null
	}
}
